apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: slave-partition-2
spec:
  action: partition
  mode: all
  selector:
    pods:
      "default":
        - redis-0
        - redis-sentinel-2
  direction: both
  target:
    selector:
      pods:
        "default":
          - redis-1
          - redis-sentinel-0
          - redis-sentinel-1
    mode: all
